#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
set -o errexit
set -o nounset
set -o pipefail

# -----------------------------------------------------------------------------
# Globals
# -----------------------------------------------------------------------------
declare -r WORK_DIR="$(dirname ${0})/.."
declare -r BASE_DIR=${HOME}/tmp/easy-ca-${RANDOM}
declare -r ROOT_CA_DIR=${BASE_DIR}/root
declare -r SIGNING_CA_DIR=${BASE_DIR}/signing

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
function test::setup() {
  [[ ! -d ${BASE_DIR} ]] && mkdir -p ${BASE_DIR}
}

function test::create_root_ca() {
  printf "%0.0s\n" {0..10} | \
    ${WORK_DIR}/create-root-ca -d ${ROOT_CA_DIR}
}

function test::create_signing_ca() {
  printf "%0.0s\n" {0..11} | \
    ${ROOT_CA_DIR}/bin/create-signing-ca -d ${SIGNING_CA_DIR}
}

function test::create_server_certificate() {
  printf "%0.0s\n" {0..6} | \
    ${SIGNING_CA_DIR}/bin/create-server -s \*.acme.com -a acme.com
}

function test::create_ssl_certificate() {
  printf "%0.0s\n" {0..6} | \
    ${SIGNING_CA_DIR}/bin/create-ssl -s ssl.acme.com -a acme.com
}

function test::create_client_certificate() {
  printf "%0.0s\n" {0..6} | \
    ${SIGNING_CA_DIR}/bin/create-client -c bob -n bob_builder
}

function test::revoke_certificate() {
  local certificate=${1}; shift; 
  printf "1\ny\n" | \
    ${SIGNING_CA_DIR}/bin/revoke-cert \
    -c ${SIGNING_CA_DIR}/certs/${certificate}
}

function test::usage() {
  local scripts=( "${@}" )
  for script in "${scripts[@]}"; do
    ${SIGNING_CA_DIR}/bin/${script} -h
  done
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
test::setup
test::create_root_ca
test::create_signing_ca
test::create_server_certificate
test::create_ssl_certificate
test::create_client_certificate
test::revoke_certificate "star-acme-com.server.crt"
test::revoke_certificate "ssl-acme-com.server.crt"
test::revoke_certificate "bob-builder.client.crt"
test::usage \
  create-client \
  create-client-o \
  create-root-ca \
  create-server \
  create-signing-ca \
  create-ssl \
  revoke-cert
