#!/bin/bash
# Derek Moore <derek.moore@gmail.com>

# -----------------------------------------------------------------------------
# Globals
# -----------------------------------------------------------------------------
declare -r SCRIPT=${0##*/}
declare    CLIENT_NAME=
declare    BIN_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
function usage() {
  local exit_code=${1:-1}

  cat <<USAGE

  Usage:
    ${SCRIPT} -c CLIENT_NAME

  Issues a client certificate for CLIENT_NAME

  Options:
    -c CLIENT_NAME  Client name (commonName) for the new cert

USAGE
  exit ${exit_code}
}

function parse_options() {
  while getopts hc: flag; do
    case ${flag} in
    c) CLIENT_NAME=${OPTARG};;
    h) usage 0;;
    *) usage 1;;
    esac
  done
}

function validate_options() {
  if [[ -z ${CLIENT_NAME} ]]; then
    usage 1
  fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
parse_options "${@}"
validate_options

source ${BIN_DIR}/functions
source ${BIN_DIR}/defaults.conf

SAFE_NAME=$(to_safe_name "${CLIENT_NAME}")

message "Creating new client certificate for '${CLIENT_NAME}'"


pushd ${BIN_DIR}/.. > /dev/null

if [ -f conf/${SAFE_NAME}.client.conf ]; then
    echo "Configuration already exists for '${CLIENT_NAME}', exiting."
    exit 1
fi

echo -n "Enter passphrase for signing CA key: "
read -s PASS
echo
export CA_PASS=${PASS}

# Generate the client cert openssl config
export SAN=""
export CA_USERNAME=${CLIENT_NAME}
template "${BIN_DIR}/templates/client.tpl" "conf/${SAFE_NAME}.client.conf"

# Create the client key and csr and sign it
create_csr "client" "${SAFE_NAME}"
sign_csr "client" "${SAFE_NAME}"
popd > /dev/null

message "Client certificate created."
