#!/bin/bash
# Derek Moore <derek.moore@gmail.com>

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
set -o errexit
set -o nounset
set -o pipefail

# -----------------------------------------------------------------------------
# Globals
# -----------------------------------------------------------------------------
declare -r SCRIPT=${0##*/}
declare -x SAN=${SAN:-}
declare    CA_DIR=
declare    BIN_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
function usage() {
  local exit_code=${1:-1}
  cat <<USAGE

  Usage:
    ${SCRIPT} -d CA_DIR

  Initializes a new root CA in CA_DIR

  Options:
    -d CA_DIR  Target directory to be created and initialized

USAGE
  exit ${exit_code}
}

function parse_options() {
  while getopts hd: flag; do
    case ${flag} in
    d) CA_DIR=${OPTARG} ;;
    h) usage 0;;
    *) usage 1;;
    esac
  done
}

function validate_options() {
  if [[ -z ${CA_DIR} ]]; then
    usage 1
  fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
parse_options "${@}"
validate_options

source ${BIN_DIR}/functions
[[ -f "${BIN_DIR}/defaults.conf" ]] && source ${BIN_DIR}/defaults.conf

CA_NAME=$( basename "${CA_DIR}" )

message "Creating root CA in '${CA_DIR}'"

init_ca_home ${CA_DIR}
generate_conf ${CA_DIR}/bin/defaults.conf
source ${CA_DIR}/bin/defaults.conf
ask_passphrase "${CA_NAME}"

pushd ${CA_DIR} > /dev/null

# Generate the root CA openssl config
template "${BIN_DIR}/templates/root.tpl" "conf/ca.conf"

# Create the root CA csr
openssl genrsa -out ca/private/ca.key -passout env:CA_PASS 4096
chmod 0400 ca/private/ca.key

# Create the root CA csr
openssl req -new -batch \
            -config conf/ca.conf \
            -key ca/private/ca.key \
            -out ca/ca.csr \
            -passin env:CA_PASS

# Create the root CA certificate
openssl ca -selfsign -batch -notext \
           -config conf/ca.conf \
           -in ca/ca.csr \
           -out ca/ca.crt \
           -days 3652 \
           -extensions root_ca_ext \
           -passin env:CA_PASS

# Create the root CRL
openssl ca -gencrl -batch \
           -config conf/ca.conf \
           -out crl/ca.crl

# Replicate the existing binary directory
copy_scripts

popd > /dev/null


message "Root CA initialized."
