#!/bin/bash
# Derek Moore <derek.moore@gmail.com>

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
set -o errexit
set -o nounset
set -o pipefail

# -----------------------------------------------------------------------------
# Globals
# -----------------------------------------------------------------------------
declare -r SCRIPT=${0##*/}
declare    CLIENT_NAME=
declare    SAFE_NAME=
declare    BIN_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
declare -x SAN=""

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
function usage() {
  local exit_code=${1:-1}

  cat <<USAGE

  Usage:
    ${SCRIPT} -c CLIENT_NAME

  Issues a client certificate for CLIENT_NAME

  Options:
    -c CLIENT_NAME  Client name (commonName) for the new cert

USAGE
  exit ${exit_code}
}

function parse_options() {
  while getopts hc: flag; do
    case ${flag} in
    c) CLIENT_NAME=${OPTARG};;
    h) usage 0;;
    *) usage 1;;
    esac
  done
}

function validate_options() {
  if [[ -z ${CLIENT_NAME} ]]; then
    usage 1
  fi
}

function source_files() {
  source ${BIN_DIR}/functions
  [[ -f "${BIN_DIR}/defaults.conf" ]] &&
    source ${BIN_DIR}/defaults.conf
}

function create_safe_name() {
  SAFE_NAME=$(to_safe_name "${CLIENT_NAME}")
}

function create_client_conf() {
  # Generate the client cert openssl config
  export CA_USERNAME=${CLIENT_NAME}
  template "${BIN_DIR}/templates/client.tpl" "conf/${SAFE_NAME}.client.conf"
  if [[ -z ${SAN} ]]; then
    sed -i -e 's/^\(subjectAltName.*=.*\)/#\1/' \
      "conf/${SAFE_NAME}.client.conf"
  fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
parse_options "${@}"
validate_options
source_files
create_safe_name
message "Creating new client certificate for '${CLIENT_NAME}'"
pushd ${BIN_DIR}/.. > /dev/null
check_existing_configuration "${SAFE_NAME}" client
create_client_conf
ask_ca_passphrase 'signing'
create_csr "client" "${SAFE_NAME}"
sign_csr "client" "${SAFE_NAME}"
popd > /dev/null
message "Client certificate created."
