#!/bin/bash
# Derek Moore <derek.moore@gmail.com>
# Changed by fcgdam

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
set -o errexit
set -o nounset
set -o pipefail

# -----------------------------------------------------------------------------
# Globals
# -----------------------------------------------------------------------------
declare -r SCRIPT=${0##*/}
declare    SERVER_NAME=
declare    ALT_NAME=

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
function usage() {
  local exit_code=${1:-1}
  cat <<USAGE

  Usage:
    ${SCRIPT} -s SERVER_NAME [-a ALT_NAME]...

  Issues a server SSL certificate for SERVER_NAME

  Options:
    -s SERVER_NAME  Server hostname (commonName) for the new cert
    -a ALT_NAME     One (or more) subjectAltNames for the new cert (optional)

USAGE
  exit ${exit_code}
}

function parse_options() {
  while getopts hs:a: flag; do
    case ${flag} in
    s) SERVER_NAME=${OPTARG}
      if [ -z "${ALT_NAME}" ]; then
        ALT_NAME="DNS:${OPTARG}"
      else
        ALT_NAME="${ALT_NAME}, DNS:${OPTARG}"
      fi
      ;;
    a)
      if [ -z "${ALT_NAME}" ]; then
        ALT_NAME="DNS:${OPTARG}"
      else
        ALT_NAME="${ALT_NAME}, DNS:${OPTARG}"
      fi
      ;;
    h) usage 0;;
    *) usage 1;;
    esac
  done
}

function validate_options() {
  if [[ -z ${SERVER_NAME} ]]; then
    usage 1
  fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
parse_options "${@}"
validate_options

BIN_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source ${BIN_DIR}/functions
source ${BIN_DIR}/defaults.conf

# Sanitize the commonName to make it suitable for use in filenames
SAFE_NAME=`echo ${SERVER_NAME} | sed 's/\*/star/g'`
SAFE_NAME=`echo ${SAFE_NAME} | sed 's/[^A-Za-z0-9-]/-/g'`

message \
  "Creating new SSL server certificate for:" \
  "commonName: '${SERVER_NAME}'" \
  "subjectAltName: '${ALT_NAME}'"

pushd ${BIN_DIR}/.. > /dev/null

if [ -f conf/${SAFE_NAME}.server.conf ]; then
    echo "Configuration already exists for '${SERVER_NAME}', exiting."
    exit 1
fi

echo -n "Enter passphrase for signing CA key: "
read -s PASS
echo
export CA_PASS=${PASS}

# Generate the server openssl config
export CA_HOSTNAME=${SERVER_NAME}
export SAN=${ALT_NAME}
template "${BIN_DIR}/templates/ssl.tpl" "conf/${SAFE_NAME}.server.conf"

# Create the server key and csr
openssl req -new -nodes \
            -config conf/${SAFE_NAME}.server.conf \
            -keyout private/${SAFE_NAME}.server.key \
            -out csr/${SAFE_NAME}.server.csr
chmod 0400 private/${SAFE_NAME}.server.key

# Create the server certificate
openssl ca -batch -notext \
           -config conf/ca.conf \
           -in csr/${SAFE_NAME}.server.csr \
           -out certs/${SAFE_NAME}.server.crt \
           -days 730 \
           -extensions server_ext \
           -passin env:CA_PASS

popd > /dev/null

message "Server certificate created."
