#!/usr/bin/env bash
# Derek Moore <derek.moore@gmail.com>

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
set -o errexit
set -o nounset
set -o pipefail

# -----------------------------------------------------------------------------
# Global
# -----------------------------------------------------------------------------
declare -r SCRIPT=${0##*/}
declare -- CERT_NAME=
declare -- BIN_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
declare -x SAN=${SAN:-}
declare -x CA_PASS=${CA_PASS:-}

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
function usage() {
  local exit_code=${1:-1}
  cat <<USAGE

  Usage:
    ${SCRIPT} -C CERT_NAME [-h]

  Description:
    Revokes a certificate issued by this CA.

  Options:
    -h | --help                  This message.
    -C | --cert-name CERT_NAME   Path the the certificate file to be revoked.

USAGE
  exit ${exit_code}
}

function parse_options() {
  while (( $# > 0 )); do
    case ${1} in
    -C|--cert-name) shift; CERT_NAME=${1};;
    -h|--help)      usage 0;;
    *)              usage 1;;
    esac
    shift
  done
}

function validate_options() {
  if [[ -z ${CERT_NAME} ]]; then
    usage 1
  fi
}

function source_files() {
  source ${BIN_DIR}/functions
  [[ -f "${BIN_DIR}/defaults.conf" ]] &&
    source ${BIN_DIR}/defaults.conf
}

function check_certificate() {
  local certificate=${1}; shift;
  if [ ! -f "${certificate}" ]; then
    echo "Could not read certificate '${certificate}', exiting."
    exit 1
  fi
}

function ask_revoke_reason() {
  local -a reasons=(
    unspecified
    keyCompromise
    CACompromise
    affiliationChanged
    superseded
    cessationOfOperation
    certificateHold
  )

  PS3="Enter 1-${#reasons[@]}: "
  echo "Reason for revocation: "
  select reason in ${reasons[@]}; do
    if (( ${REPLY} > ${#reasons[@]} )); then
      echo "Unknown reason, exiting."
      exit 128
    fi
    REASON=${reason}
    break
  done

  echo "You are about to revoke this certificate with reason '${REASON}'."
  echo -n "Are you SURE you wish to continue? [y/N]: "
  read SURE
  if [ "${SURE}" != "y" -a "${SURE}" != "Y" ]; then
    echo "Exiting."
    exit 1
  fi
}

function revoke_certificate() {
  openssl ca \
    -config conf/ca.conf \
    -revoke ${CERT_NAME} \
    -crl_reason ${REASON} \
    -passin env:CA_PASS
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
parse_options "${@}"
validate_options
source_files
check_certificate "$(fullpath ${CERT_NAME})"
message "Revoking certificate '${CERT_NAME}'"
pushd ${BIN_DIR}/.. > /dev/null
ask_revoke_reason
revoke_certificate
create_ca_crl
popd > /dev/null
message "Certificate '${CERT_NAME}' revoked."
