# -----------------------------------------------------------------------------
# Verify bash compatibility
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.0
# -----------------------------------------------------------------------------
name: bash-compatibility

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master

jobs:
  bash-compatibility:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        bash:
        - '3.0'
        - '3.1'
        - '3.2'
        - '4.0'
        - '4.1'
        - '4.2'
        - '4.3'
        - '4.4'
        - '5.0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Loop test
      shell: bash
      run: |
        docker run \
          --tty \
          --volume $(pwd):/easy-ca \
          bash:${{ matrix.bash }} \
          bash -c "apk add --update openssl && bash /easy-ca/test/test-easy-ca"
