# -----------------------------------------------------------------------------
# Verify bash compatibility
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.3.0
# -----------------------------------------------------------------------------
name: bash-compatibility

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  bash-compatibility:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: bash:${{ matrix.bash }}
    strategy:
      fail-fast: false
      matrix:
        bash:
          - '3.0'
          - '3.1'
          - '3.2'
          - '4.0'
          - '4.1'
          - '4.2'
          - '4.3'
          - '4.4'
          - '5.0'
          - '5.1'
          - '5.2'

    steps:
    - name: Install dependencies
      shell: bash
      run: |
        apk add --update \
          git \
          git-lfs \
          openssl

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Check bash compatibilty
      shell: bash
      run: bash test/test-easy-ca
