# -----------------------------------------------------------------------------
# Verify easy-ca's CA and certification creation
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.1
# -----------------------------------------------------------------------------
name: verify-ca

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master

jobs:
  verify-ca:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - ubuntu-16.04
        #- macos-11.0
        - macos-10.15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Test creation of CA and certificiates
      shell: bash
      run: test/test-easy-ca
      timeout-minutes: 5
